[entity]
"9 lives cat" = false
"Baby nametag" = true
"Brushable parrot/chicken" = true
"Chicken egg try hatch on despawn" = true
"Explosive sniffer" = true
"Fox auto breed from berries" = true
"Fox bury items" = true
"Horse can seat on boat" = true
"Pat you pets" = true
"Piglin treats golden trimmed armor as golden armor" = true
"No saddled mobs wandering" = true
"Rabbit breed after eats carrot crops" = true
"Random size fishes/squid" = true
"Silent nametag" = true
"Smaller bee" = true
"Sniffer sniff moss block" = true
"Snow Golem produces powder snow" = true
"Wandering trader announcer" = true

[general]
"Banner trophies" = true
"Beacon extended" = true
"Bigger radius bookshelf for enchanting table" = true
"Bonemeal coral fan/block" = true
"Bonemeal small flowers" = true
"Bundle's Enchantment" = true
"Wash filled map with Cauldron" = true
"Click through sign/itemframe" = true
"1 tick delay copper bulb" = false
"Day counter" = 0
"Message tick speed" = 3
"Ticks per day" = 24000
"Deepslate generator" = true
"Faster minecart" = true
"Faster oxidization" = true
"Glow berry gives glow effect" = true
"Invisible item frame" = true
"Backup Enchantments" = true
"Mud support sugarcane" = true
"No level limit anvil" = true
"Prevent farmland trampling" = true
"No set spawn on sleep" = true
"Shulker label" = true
"Sleep doesn't skip weather" = "DISABLE"			# [DISABLE, RAIN_ONLY, ALL_WEATHER]
"Sneak through sweet berry" = true
"Torch burns target" = true
"Usable suspicious block" = true
"Wet sponge dry in warm biome" = true
"XP crops" = true

[item]
"Bundle place function" = true
"Check Villagers schedule" = true
"Clock shows current time" = true
"Hoe harvests crops" = "ALL"
"Mace rotate blocks" = true
"Shear can pickpocket villager" = true
"Shear can defuse TNT" = true
"Shear prevents plant from growing" = true
"Slime chunk detector" = true
"Spyglass what is that?" = "ALL"			# [ALL, BLOCK_ONLY, ENTITY_ONLY, DISABLE]
"Normal inspect range" = 5
"Normal mode: Show block's name" = true
"Normal mode: Show block's direction" = true
"Normal mode: Show distance" = false
"Normal mode: Show hidden infos" = true
"Inspect range when zooming" = 32
"Zoom mode: Show block's name" = true
"Zoom mode: Show block's direction" = true
"Zoom mode: Show distance" = true
"Zoom mode: Show hidden infos" = true
"Trident can call thunder storm" = true
"Waxed copper indicator" = true

[recipe]
"Bundle recipe" = true
"Suspicious sand/gravel recipe" = true

[compatibility]
"EasyShulkerBoxes Compatibility Layer" = true
"Enchancement Compatibility Layer" = true

[command]
"Emote commands" = true
"Enable permission system" = false

[cursed]
"End stone is cheese" = false
"Hydrophobic elytra" = false
"Reverse phantom spawn condition" = false

