["Homebound Configs"]
	# Default: 15
	# Range: > 0
	"Homeward Bone Use Time" = 2
	#How long it takes (in seconds) to bind your home to a location when you are crouching and using a homebound stone.
	# Default: 3
	# Range: > 0
	"Bind Home Use Duration" = 2
	#General
	#When you take damage while using a homebound item to teleport home the teleport is canceled and a cooldown is added before you can use it again.
	#This is to prevent players from easily teleporting out of a dangerous situation.
	#This value is how long of a cooldown in seconds is added when damage is taken. Set to 0 to disable taking damage from canceling the teleport
	# Default: 5
	# Range: > 0
	"Hurt Cooldown Time" = 5
	#Cooldown duration triggered when settings your home in seconds. If 0 then setting your home does not put your teleport on cooldown.
	#If set to 3600 then this will add a 1 hour cooldown to your teleport whenever you set your home. This is cumulative to your current teleport cooldown.
	#This means if your teleport is already on a 30 minute cooldown and the value is 3600, your new cooldown is 1 hour 30 minutes.
	#If you don't have the Cant Bind Home On Cooldown option turned on then you could potentially accrue huge cooldown timers.
	# Default: 0
	# Range: > 0
	"Bind Home Cooldown Duration" = 0
	#If you can bind a home while your warp is on cooldown.
	#If true then you can only bind your home while your teleport is on cooldown. If false then you can set your home anytime.
	"Cant Bind Home On Cooldown" = false
	#Adding a dimension to this list will prevent you from setting your home while in this dimension.
	#If you wanted to prevent players from setting their home in the end you would add minecraft:the_end
	"Home Dimension Blacklist" = []
	#Adding a dimension to this list will prevent you from using your homebound stone while in the dimension, as well as setting your home there.
	#If you wanted to prevent players from using homebound stones and setting their home in the end you would add minecraft:the_end
	"Teleport Dimension Blacklist" = []
	#Adding a dimension to this list will prevent you from using your homebound stone while in the structure, as well as setting your home there.
	#If you wanted to prevent players from using homebound stones and setting their home in a bastion you would add minecraft:bastion
	"Teleport Structure Blacklist" = []
	#How far away you must be from the nearest hostile mob in order to begin teleporting.
	#I set the max to 32 blocks (2 chunks) for performance reasons.
	# Default: 0
	# Range: 0 ~ 32
	"Minimum Mob Distance" = 0
	#Slows the player by this amount when using a homebound stone. 1.0 means completely stopped, 0.0 means no slow applied.
	# Default: 0.7
	# Range: 0.0 ~ 1.0
	"Channel Slow Percentage" = 0.7
	#Homeward Item Cooldowns
	#All cooldowns are in minutes. All enchantments or cooldown reducing effects will apply to this base cooldown.
	#All use times are in seconds. This is the length of time it takes to activate the stone.
	#All max distances are in blocks. 16 blocks per chunk, so 160 blocks is 10 chunks. Having a value of 0 means no max distance.
	#Dimensional travel determines if the item can teleport you home from another dimension or not.
	#Blocks per bonus reduced means the number of blocks it takes to reduce the cooldown reduction effect by 1%. If this is set to 50 and the maximum distance reduction multiplier is 0.4 (or 40% cooldown reduction) and you are 51 blocks away from home, the cooldown reduction effect is now 0.39 (39%).
	#If this is set to 50 and the maximum distance reduction multiplier is 0.4 (or 40% cooldown reduction) and you are 51 blocks away from home, the cooldown reduction effect is now 0.39 (39%).
	#This will reduce by 1% for every 50 blocks away from home until the bonus is no longer applied at 0%. In the example above that would be 2000 blocks.
	#--- Homeward Bone ---
	# Default: 120
	# Range: > 0
	"Homeward Bone Cooldown" = 120
	# Default: 0
	# Range: > 0
	"Homeward Bone Max Distance" = 0
	"Homeward Bone Dimensional travel allowed" = true
	#--- Hearthwood ---
	# Default: 10
	# Range: > 0
	"Hearthwood Cooldown" = 10
	# Default: 3
	# Range: > 0
	"Hearthwood Use Time" = 3
	# Default: 160
	# Range: > 0
	"Hearthwood Max Distance" = 160
	"Hearthwood Dimensional travel allowed" = false
	#--- Homeward Gem ---
	# Default: 60
	# Range: > 0
	"Homeward Gem Cooldown" = 60
	# Default: 12
	# Range: > 0
	"Homeward Gem Use Time" = 12
	# Default: 600
	# Range: > 0
	"Homeward Gem Max Distance" = 600
	"Homeward Gem Dimensional travel allowed" = false
	#--- Homeward Stone ---
	# Default: 60
	# Range: > 0
	"Homeward Stone Cooldown" = 60
	# Default: 10
	# Range: > 0
	"Homeward Stone Use Time" = 10
	# Default: 0
	# Range: > 0
	"Homeward Stone Max Distance" = 0
	"Homeward Stone Dimensional travel allowed" = false
	#--- Haven Stone ---
	# Default: 60
	# Range: > 0
	"Haven Stone Cooldown" = 60
	# Default: 10
	# Range: > 0
	"Haven Stone Use Time" = 10
	# Default: 0
	# Range: > 0
	"Haven Stone Max Distance" = 0
	"Haven Stone Dimensional travel allowed" = true
	#--- Dawn Stone ---
	# Default: 50
	# Range: > 0
	"Dawn Stone Cooldown" = 50
	# Default: 9
	# Range: > 0
	"Dawn Stone Use Time" = 9
	# Default: 0
	# Range: > 0
	"Dawn Stone Max Distance" = 0
	"Dawn Stone Dimensional travel allowed" = true
	#--- Sun Stone ---
	# Default: 45
	# Range: > 0
	"Sun Stone Cooldown" = 45
	# Default: 8
	# Range: > 0
	"Sun Stone Use Time" = 8
	# Default: 0
	# Range: > 0
	"Sun Stone Max Distance" = 0
	"Sun Stone Dimensional travel allowed" = true
	#--- Dusk Stone ---
	# Default: 60
	# Range: > 0
	"Dusk Stone Cooldown" = 60
	# Default: 10
	# Range: > 0
	"Dusk Stone Use Time" = 10
	# Default: 0
	# Range: > 0
	"Dusk Stone Max Distance" = 0
	"Dusk Stone Dimensional travel allowed" = true
	# Default: 40
	# Range: > 0
	"Dusk Stone Blocks Per Percent Reduced" = 40
	# Default: 0.6
	# Range: 0.0 ~ 1.0
	"Dusk Stone Maximum Distance Reduction Multiplier" = 0.6
	#--- Twilight Stone ---
	# Default: 60
	# Range: > 0
	"Twilight Stone Cooldown" = 60
	# Default: 10
	# Range: > 0
	"Twilight Stone Use Time" = 10
	# Default: 0
	# Range: > 0
	"Twilight Stone Max Distance" = 0
	"Twilight Stone Dimensional travel allowed" = true
	# Default: 40
	# Range: > 0
	"Twilight Stone Blocks Per Percent Reduced" = 40
	# Default: 0.7
	# Range: 0.0 ~ 1.0
	"Twilight Stone Maximum Distance Reduction Multiplier" = 0.7
